<?php


/**
 * Template for individual blog post item in the slider
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */

$_post = $block->getData('item');

// Get image helper
$imageHelper = $this->helper(\MageOS\Blog\Helper\Image::class);
$width = 700; // Default width

// Get featured image
$featuredImage = $_post->getFeaturedListImg() ?: $_post->getFeaturedImg();
$featuredImage = $imageHelper->init($featuredImage)->resize($width, null, false);
if (!$_post->getFeaturedListImg() && !$_post->getFeaturedImg()) {
    $featuredImage = $block->getViewFileUrl('MageOS_Blog::images/default-no-image.png');
}


$_postUrl = $block->escapeUrl($_post->getPostUrl());
$_postName = $block->escapeHtml($_post->getTitle());
?>

<div class="blog-post-slider-item flex flex-col h-full">
    <!-- img container -->
    <div class="image-container rounded-md">
        <!-- post image -->
        <a class="image-wrap" href="<?= $block->escapeUrl($_post->getPostUrl()) ?>" title="<?= $block->escapeHtml($_post->getTitle()) ?>">
            <img class="w-full bg-img mageos_blogunveil"
                 src="<?= $block->escapeUrl($featuredImage) ?>"
                 alt="<?= $block->escapeHtml($_post->getTitle()) ?>"
                 loading="lazy" />
        </a>

        <!-- post category -->
        <span class="post-category">
            <?php foreach ($_post->getParentCategories() as $ct) { ?>
                <a class="category-name" href="<?= $block->escapeUrl($ct->getCategoryUrl()) ?>" title="<?= $block->escapeHtml($ct->getTitle()) ?>">
                    <?= $block->escapeHtml($ct->getTitle()) ?>
                </a>
            <?php } ?>
        </span>
    </div>

    <!-- post data -->
    <div class="post-data-wrap flex justify-between !mt-6">
            <span class="post-data">
                <?= $block->escapeHtml($_post->getPublishDate()) ?>
            </span>
    </div>

    <!-- post info -->
    <div class="post-info">
        <!-- post title -->
        <h3 class="post-title">
            <a href="<?= $block->escapeUrl($_post->getPostUrl()) ?>" class="hover:text-primary text-lg font-semibold">
                <?= $block->escapeHtml($_post->getTitle()) ?>
            </a>
        </h3>
    </div>

    <!-- post description -->
    <div class="post-description my-4 text-sm font-normal">
        <?= /*@noEscape*/ $_post->getShortFilteredContentWithoutImages() ?>
    </div>

    <!-- read more -->
    <div class="post-read-more mt-auto">
        <a class="action primary btn btn-primary w-fit" href="<?= /*@noEscape*/ $_postUrl ?>" title="<?= /*@noEscape*/ $_postName ?>">
            <?= $block->escapeHtml(__('Read more')) ?>
        </a>
    </div>
</div>
